### PR TITLE
build: fixes for linux aarch64

### PR DESCRIPTION
**Pull request by jcelerier**
The code currently does not build on AArch64, this fixes that.
That said, from the code it seems like it would break on Intel instead due to 

```
#ifdef tfxINTEL
const tfx128Array tfxF3_4 = tfx128SetConst(1.0f / 3.0f);
const tfx128Array tfxF2_4 = tfx128SetConst(.366025403f);
const tfx128Array tfxG2_4 = tfx128SetConst(0.211324865f);
const tfx128Array tfxG2_4x2 = tfx128SetConst(0.42264973f);
const tfx128Array tfxG3_4 = tfx128SetConst(1.0f / 6.0f);
const tfx128Array tfxG32_4 = tfx128SetConst((1.0f / 6.0f) * 2.f);
const tfx128Array tfxG33_4 = tfx128SetConst((1.0f / 6.0f) * 3.f);
const tfx128iArray tfxONE = tfx128SetConst(1);
const tfx128Array tfxONEF = tfx128SetConst(1.f);
const tfx128Array tfxZERO = tfx128SetConst(0.f);
const tfx128Array tfxTHIRTYTWO = tfx128SetConst(32.f);
const tfx128iArray tfxFF = tfx128SetConst(0xFF);
const tfx128Array tfxPSIX = tfx128SetConst(0.6f);
#elif defined(tfxARM)
const tfx128 tfxF3_4 = vdupq_n_f32(1.0f / 3.0f);
const tfx128 tfxF2_4 = vdupq_n_f32(.366025403f);
const tfx128 tfxG2_4 = vdupq_n_f32(0.211324865f);
const tfx128 tfxG2_4x2 = vdupq_n_f32(0.42264973f);
const tfx128 tfxG3_4 = vdupq_n_f32(1.0f / 6.0f);
const tfx128 tfxG32_4 = vdupq_n_f32((1.0f / 6.0f) * 2.f);
const tfx128 tfxG33_4 = vdupq_n_f32((1.0f / 6.0f) * 3.f);
const tfx128i tfxONE = vdupq_n_s32(1);
const tfx128 tfxONEF = vdupq_n_f32(1.f);
const tfx128 tfxZERO = vdupq_n_f32(0.f);
const tfx128 tfxTHIRTYTWO = vdupq_n_f32(32.f);
const tfx128i tfxFF = vdupq_n_s32(0xFF);
const tfx128 tfxPSIX = vdupq_n_f32(0.6f);
#endif
```

which means that the intel version pf `tfxF3_4` have a .m and not the arm version

### CODE REVIEW

**Comment by jcelerier** [comment]
I'll gladly add a small CI that checks this

**Comment by jcelerier** [comment]
super :) there were also a couple other things - tfx__strcpy seems to have changed order of arguments, a function was returning true / false instead of a tfx_stream pointer, also I added an implementation of rdtsc for aarch64 found on stackoverflow

**Comment by jcelerier** [comment]
also on my platform (linux aarch64 with gcc-14 / clang-19) much more headers were required

**Comment by peterigz** [comment]
If you fancy it then you can just update the pull request to use the unions (tfx128Array) for those consts and put the .m back in the noise functions and I could probably just merge it in. I think looking at it it doesn't actually need the #ifdef tfxINTEL/tfxARM as there's no specific simd commands anymore, so can just remove the arm consts and the intel ones should just work for both...

**Comment by jcelerier** [comment]
> If you fancy it then you can just update the pull request to use the unions (tfx128Array) for those consts and put the .m 

I tried doing it but then for some it failed: e.g. the initialization of 
  
     const tfx128Array tfxF3_4 = vdupq_n_f32(1.0f / 3.0f);

does not work (likely it's not too much but as you say maybe it's better to uniformize whatever can be uniformized between the two cases ?)

**Comment by peterigz** [comment]
Does it work if you just remove the arm consts and just use the intel version for both? :
const tfx128Array tfxF3_4 = tfx128SetConst(1.0f / 3.0f);
const tfx128Array tfxF2_4 = tfx128SetConst(.366025403f);
const tfx128Array tfxG2_4 = tfx128SetConst(0.211324865f);
const tfx128Array tfxG2_4x2 = tfx128SetConst(0.42264973f);
const tfx128Array tfxG3_4 = tfx128SetConst(1.0f / 6.0f);
const tfx128Array tfxG32_4 = tfx128SetConst((1.0f / 6.0f) * 2.f);
const tfx128Array tfxG33_4 = tfx128SetConst((1.0f / 6.0f) * 3.f);
const tfx128iArray tfxONE = tfx128SetConst(1);
const tfx128Array tfxONEF = tfx128SetConst(1.f);
const tfx128Array tfxZERO = tfx128SetConst(0.f);
const tfx128Array tfxTHIRTYTWO = tfx128SetConst(32.f);
const tfx128iArray tfxFF = tfx128SetConst(0xFF);
const tfx128Array tfxPSIX = tfx128SetConst(0.6f);

the macro is simply #define tfx128SetConst(value) {value, value, value, value} so it should do in theory.

**Comment by peterigz** [comment]
I have this building on Mac now so I'm hoping linux should be fine now. Thanks for the heads up on the missing headers and other bits! Let me know if Linux has any issues, at some point I'll set up some linux distribution here to test on and get the editor building.

**Comment by jcelerier** [comment]
wops sorry ! forgot to come back to this. I will try on linux and report

**Pull request closed without merging**
